apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-kube-spring-app.fullname" . }}
  labels:
{{ include "test-kube-spring-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "test-kube-spring-app.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
