apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kube-spring-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-kube-spring-app
  template:
    metadata:
      labels:
        app: test-kube-spring-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
      volumes:
        - name: test-kube-spring-app
          configMap:
            name: test-kube-spring-app
            items:
              - key: application.yml
                path:  config-dev.yml