apiVersion: v1
kind: Service
metadata:
  name: test-kube-spring-app
  labels:
    name: test-kube-spring-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: test-kube-spring-app
