apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-kube-spring-app.fullname" . }}
  labels:
{{ include "test-kube-spring-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "test-kube-spring-app.fullname" . }}
