server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: "always"

spring:
  application:
    name: test-kube-spring-app

  main:
    banner-mode: "off"

  redis:
    host: my-release-redis-master
    port: 6379